# Generated by Django 2.2.5 on 2019-10-03 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fstname', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('creteddate', models.DateField()),
                ('email', models.CharField(max_length=30)),
            ],
        ),
    ]
