# Generated by Django 2.2.5 on 2019-10-09 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_userdata_lstname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='creteddate',
        ),
    ]
