# Generated by Django 2.2.5 on 2019-10-10 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_fir'),
    ]

    operations = [
        migrations.AddField(
            model_name='fir',
            name='addr',
            field=models.CharField(default='ddddd', max_length=50),
        ),
        migrations.AddField(
            model_name='fir',
            name='firdesc',
            field=models.CharField(default='no', max_length=1000),
        ),
        migrations.AddField(
            model_name='fir',
            name='firstation',
            field=models.CharField(default='ddddd', max_length=50),
        ),
        migrations.AddField(
            model_name='fir',
            name='firtype',
            field=models.CharField(default='ddddd', max_length=50),
        ),
        migrations.AddField(
            model_name='fir',
            name='name',
            field=models.CharField(default='ddddd', max_length=50),
        ),
    ]
